### ISSUE TITLE
See attached images for examples 

### ISSUE THREAD

**Issue by Tyler-Lauricella** [Papadaplus/Papadaplus.github.io#2]
![konner](https://user-images.githubusercontent.com/120280252/217407566-d2f0e64c-df48-46c9-ad22-2c0edfa1f045.PNG)
![konner2](https://user-images.githubusercontent.com/120280252/217407584-7052a4d4-2cab-4900-acde-658b73dcec01.PNG)

**Comment by Papadaplus** [comment]
Thanks for all the format suggestions! I have fixed a lot of the spacing issues you have pointed out for my website. Along with the sizing and coloring you pointed out.
